### ISSUE TITLE
Domain Release?

### ISSUE THREAD

**Issue by jalavoy** [durzel/wormhol.es#1]
Hey man, I evemailed about this, but considering you probably wont see it, figured i'd reach out here.

I'd be willing to take over hosting the site if you're willing to transfer the domain to me. I like the idea of it staying open source like this, but I'd love for the codebase to live on under it's original domain.

If you're interested in this at all, shoot me some contact information and we can talk further. 

Thanks man, best of luck.

**Comment by durzel** [comment]
Hi @jalavoy 

Feels a bit silly commenting over 6 years later, but I somehow only just saw this.  Apologies for not replying at the time.  I'm probably not going to do anything with the domain, but if I change my mind (and you're still interested) I'll let you know.  Again, sorry for the long delay.

**Comment by jalavoy** [comment]
@durzel talk about necroposting lmao. 

No worries dude. I'm not playing anymore anyway. Best of luck in the future.

**Comment by durzel** [comment]
You too.. I just felt bad when I came across this and noticed you closed it 2 years later after asking, with no response.  All the best :)
